# Generated by Django 5.0.1 on 2025-02-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yatraapp', '0003_alter_booking_table_alter_tourpackage_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
